---

# tasks file for CentOS

- name: "Install httpd package"
  package:
    name: "httpd-{{ httpd_version }}"
#    state: present

- name: "Install firewalld package"
  package:
    name: firewalld
    state: present


- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled

- name: "Create document root"
  file:
      path: "/var/www/{{ ap_http_host_dir }}"
      state: directory

- name: "Copy source code/artifacts"
  copy:
      src: "{{ ap_source_code_location }}"
      dest: "/var/www/{{ ap_http_host_dir }}"

- name: "Copy conf file"
  template:
      src: "apache.conf.j2"
      dest: "/etc/httpd/conf.d/{{ ap_http_conf_file }}"
  notify: "Restart Httpd"

- name: Enable Httpd
  service:
    name: "httpd"
    enabled: yes

- name: start Httpd
  service:
    name: "httpd"
    state: started

- name: Enable firewalld
  service:
    name: "firewalld"
    enabled: yes

- name: start firewalld
  service:
    name: "firewalld"
    state: started

- name: "Add firewall rule"
  ansible.posix.firewalld:
      port: "{{ ap_http_port }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
  notify: "Restart firewalld"
  ignore_errors: True

...
