---
# defaults file for myapache

ap_additional_yum_packages:
- git

#document root directory
ap_http_host_dir: "my_host_dir"

#httpd configuration file name
ap_http_conf_file: "my_host_dir.conf"

#httpd port on which the webserver will be accessed
ap_http_port: 80

#source code location
ap_source_code_location: "files/source_code"
